### ISSUE TITLE
Issue with finding the right device

### ISSUE THREAD

**Issue by dharakyu** [alexxijielu/reverse_homology#1]
Hi Alex,

I've been trying to run your training code with the toy dataset and I've been encountering the following issue:

> 2022-03-14 18:10:56.100525: E tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Invalid argument: Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node average_pooling2d_1/AvgPool}}]]
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    model.fit_generator(train_generator, steps_per_epoch=steps, epochs=opt.epochs, use_multiprocessing=False, callbacks=[saver, csv_logger])
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3289, in __call__
    self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3222, in _make_callable
    callable_fn = session._make_callable_from_options(callable_opts)
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1489, in _make_callable_from_options
    return BaseSession._Callable(self, callable_options)
  File "/opt/conda/envs/reverse-homology/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1446, in __init__
    session._session, options_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
         [[{{node average_pooling2d_1/AvgPool}}]]

This may be related to TF being unable to detect the GPU: running `tf.test.gpu_device_name()` yields

> 022-03-14 18:02:19.346355: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2022-03-14 18:02:19.351537: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2022-03-14 18:02:19.351863: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559944070550 executing computations on platform Host. Devices:
2022-03-14 18:02:19.351898: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
''

I'm using the package versions specified in `requirements.txt` and Python 3.6.

I'm wondering if you have any ideas on how to resolve this. Thanks!

-Dhara

**Comment by alexxijielu** [comment]
Super cool you're trying out the code!

My first stab at fixing this would be replacing some of the imports (depending on the Keras/Tensorflow versions). Could you try replacing all imports from "keras" with "tensorflow.keras" in both the model and train scripts? You might also need to change "tensorflow.contrib.keras" to "tensorflow.keras" depending on your version. Let me know if this fixes it.

**Comment by dharakyu** [comment]
Hey Alex, thanks so much for the speedy response! It turns out I was using a wrong version of TF which probably caused the above issues. I then ran into some other issues with package conflicts but when I just deleted the environment and reinstalled everything, it seemed to work.
